{
 "title": "http-server-projeto-korp",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Disponibilidade do Serviço",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "service_up", "legendFormat": "Status" }
   ]
  },
  {
   "title": "Requisições por Segundo",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{endpoint}} {{status}}" }
   ]
  },
  {
   "title": "Total de Requisições Acumuladas",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "Total" }
   ]
  }
 ]
}